export const initialData = {
  products: [
    {
      titulo: "Marmita",
      slug: "marmita",
      categoria: "Equipo Militar o Camping",
      precio: 20000,
      tags: ["marmita", "marmita2"],
      images: ["/static/images/productos/marmita1.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Jarro Cantimplora",
      slug: "Jarro-cantimplora",
      categoria: "Equipo Militar o Camping",
      precio: 20000,
      tags: ["Jarro-cantimplora", "Jarro-cantimplora2"],
      images: ["/static/images/productos/jarroplastico.png"],
      copy: "jarro ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Hebilla doble puente",
      slug: "hebilla-doble-puente",
      categoria: "Herrajes",
      precio: 20000,
      tags: ["hebilla-doble-puente", "hebilla-doble-puente2"],
      images: ["/static/images/productos/hebilla.png"],
      copy: "marmita2 ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Media Luna",
      slug: "media-luna",
      categoria: "Herrajes",
      precio: 20000,
      tags: ["media-luna", "media-luna2"],
      images: ["/static/images/productos/medialuna.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Juego de Cubiertos",
      slug: "juego-de-cubiertos",
      categoria: "Institucional",
      precio: 20000,
      tags: ["juego-de-cubiertos", "juego-de-cubiertos2"],
      images: ["/static/images/productos/cubiertos.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Bandeja de compartimento",
      slug: "Bandeja-de-compartimento",
      categoria: "Institucional",
      precio: 20000,
      tags: ["Bandeja-de-compartimento", "Bandeja-de-compartimento2"],
      images: ["/static/images/productos/platopando.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Valla1",
      slug: "valla1",
      categoria: "Vallas de Contención",
      precio: 20000,
      tags: ["valla1", "valla12"],
      images: ["/static/images/productos/valla1.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Valla2",
      slug: "valla2",
      categoria: "Vallas de Contención",
      precio: 20000,
      tags: ["valla2", "valla22"],
      images: ["/static/images/productos/valla1.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Troquelado",
      slug: "troquelado",
      categoria: "Servicio de Troquelado y Embutido",
      precio: 20000,
      tags: ["troquelado", "troquelado2"],
      images: ["/static/images/productos/marmita_abierta.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Embutido",
      slug: "embutido",
      categoria: "Servicio de Troquelado y Embutido",
      precio: 20000,
      tags: ["embutido", "embutido2"],
      images: ["/static/images/productos/marmita_abierta.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Placa1",
      slug: "Placa1",
      categoria: "Placas de Identificación",
      precio: 20000,
      tags: ["Placa1", "Placa12"],
      images: ["/static/images/productos/placa.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
    {
      titulo: "Placa2",
      slug: "placa2",
      categoria: "Placas de Identificación",
      precio: 20000,
      tags: ["placa2", "placa22"],
      images: ["/static/images/productos/placa.png"],
      copy: "marmita ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan est ornare, ultricies erat a, dapibus lectus.",
    },
  ],
};
